config/routes.rb
ItineraryPlanner::Application.routes.draw do
  resources :itineraries, only: [:new, :create, :index, :show] do
    resources :waypoints, only: [:new, :create]
  end

  resources :travelers, only: [:new, :create, :index, :show]

  root 'home#index'
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  validates_presence_of :name, :origin, :destination
  has_many :waypoints
end

app/models/traveler.rb
class Traveler < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :email
  has_and_belongs_to_many :waypoints

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base
  belongs_to :itinerary
  has_and_belongs_to_many :travelers
  validates_presence_of :name, :location

  validate :occurs_on_between_itinerary_depart_and_return_dates

  def occurs_on_between_itinerary_depart_and_return_dates
    unless occurs_on.between? itinerary.depart_on, itinerary.return_on
      errors.add(
        :occurs_on, 
        "must be between the itinerary departure (#{itinerary.depart_on}) and return (#{itinerary.return_on}) dates"
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @itineraries = Itinerary.all
    @travelers = Traveler.all
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  def new
    @itinerary = Itinerary.new
  end

  def create
    @itinerary = Itinerary.create itinerary_params 
    unless @itinerary.errors.any?
      redirect_to itinerary_path(@itinerary)
    else 
      flash.now[:alert] = "Validation Errors"
      render :new
    end
  end

  def index
  end

  def show
    @itinerary = Itinerary.find params[:id]
  end

  private
  def itinerary_params
    params.require(:itinerary).permit(:name, :origin, :destination, :depart_on, :return_on)
  end
end

app/controllers/travelers_controller.rb
class TravelersController < ApplicationController
  def index
    @travelers = Traveler.all
  end

  def show
    @traveler = Traveler.find params[:id]
  end

  def new
    @traveler = Traveler.new
  end

  def create
    @traveler = Traveler.create traveler_params
    unless @traveler.errors.any?
      redirect_to @traveler
    else
      flash.now[:alert] = "Validation Errors"
      render :new
    end
  end

  private
  def traveler_params 
    params.require(:traveler).permit(:first_name, :last_name, :email)
  end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  def new
    @itinerary = Itinerary.find params[:itinerary_id]
    @waypoint = Waypoint.new(itinerary: @itinerary)
  end

  def create
    @waypoint = Waypoint.create waypoint_params
    @waypoint.travelers << Traveler.find(
      params[:waypoint][:traveler_ids].reject {|id| id.to_i == 0 }.map { |id| id.to_i }
    )
    unless @waypoint.errors.any?
      redirect_to itinerary_path(params[:itinerary_id])
    else
      flash.now[:alert] = "Validation Errors"
      @itinerary = Itinerary.find params[:itinerary_id]
      render :new
    end
  end

  private
  def waypoint_params 
    params.require(:waypoint).permit(:name, :location, :occurs_on)
      .merge(itinerary_id: params[:itinerary_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div id="itineraries">
  <h2>Current Itineraries</h2>
  <%= link_to "Add Itinerary", new_itinerary_path %>
  <% @itineraries.each do |itin| %>
    <div class='itinerary'>
      <h2>Itinerary: <%= itin.name %></h2>
      <%= render itin %>
    </div>
  <% end %>
</div>

<div id="travelers">
  <h2>Current Travelers</h2>
  <%= link_to "Add Traveler", new_traveler_path %>
  <% @travelers.each do |traveler| %>
  <div class='traveler'>
    <h2>Traveler: <%= traveler.full_name %></h2>
    <%= render traveler %>
  </div>
  <% end %>
</div>

app/views/itineraries/_itinerary.html.erb
<p>Origin: <%= itinerary.origin %></p>
<p>Destination: <%= itinerary.destination %></p>
<% unless itinerary.depart_on.blank? %>
<p>Depart on: <%= itinerary.depart_on.to_formatted_s(:long) %></p>
<% end %>
<% unless itinerary.return_on.blank? %>
<p>Return on: <%= itinerary.return_on.to_formatted_s(:long) %></p>
<% end %>

<% if itinerary.waypoints.any? %>
  <h3>Waypoints</h3>
  <% itinerary.waypoints.each do |w| %>
    <%= render w %>
  <% end %>
<% end %>

<%= link_to "Add Waypoint", new_itinerary_waypoint_path(itinerary) %>

app/views/itineraries/new.html.erb
<h2>New Itinerary:</h2>
<%= simple_form_for(@itinerary) do |f| %>
  <%= f.input :name %>
  <%= f.input :origin %>
  <%= f.input :destination %>
  <%= f.input :depart_on, as: :date %>
  <%= f.input :return_on, as: :date %>
  <%= f.button :submit, "Create" %>
<% end %>

app/views/itineraries/show.html.erb
<h2><%= @itinerary.name %></h2>
<%= render @itinerary %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ItineraryPlanner</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Itinerary Planner</h1>
<%= yield %>

</body>
</html>

app/views/travelers/_traveler.html.erb
<p>First name: <%= traveler.first_name %></p>
<p>Last name: <%= traveler.last_name %></p>
<p>Email: <%= traveler.email %></p>

app/views/travelers/index.html.erb
<% @travelers.each do |t| %>
  <%= render t %>
<% end %>

app/views/travelers/new.html.erb
<%= simple_form_for @traveler do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email, as: :email %> 
  <%= f.button :submit, "Create" %>
<% end %>

app/views/travelers/show.html.erb
<%= render @traveler %>

app/views/waypoints/_waypoint.html.erb
<p>Name: <%= waypoint.name %></p>
<p>Location: <%= waypoint.location %></p>
<p>Occurs On: <%= waypoint.occurs_on %></p>

<% if waypoint.travelers.any? %>
  <h4>Travelers:</h4>
  <% waypoint.travelers.each do |t| %>
    <%= t.full_name %>
  <% end %>
<% end %>

app/views/waypoints/new.html.erb
<h2>New Waypoint for Itinerary <%= @itinerary.name %></h2>
<%= simple_form_for [@itinerary, @waypoint] do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :occurs_on, as: :date %>
  <%= f.association :travelers, as: :check_boxes, label_method: :full_name %>
  <%= f.button :submit, "Create" %>
<% end %>